macro(TARGET_DRACO)
    set(LIBS draco dracodec dracoenc)
    find_library(LIBPATH ${LIB} PATHS )
    if (ANDROID)
        set(INSTALL_DIR ${HIFI_ANDROID_PRECOMPILED}/draco)
        target_include_directories(${TARGET_NAME} SYSTEM PRIVATE ${DRACO_INCLUDE_DIRS})
        set(LIB_DIR ${INSTALL_DIR}/lib)
        set(LIB_SEARCH_PATH_RELEASE ${LIB_DIR}/lib)
        set(LIB_SEARCH_PATH_DEBUG ${LIB_DIR}/debug/lib)
    else()
        set(LIB_SEARCH_PATH_RELEASE ${VKPKG_INSTALL_ROOT}/lib/)
        set(LIB_SEARCH_PATH_DEBUG ${VKPKG_INSTALL_ROOT}/debug/lib/)
    endif()

    foreach(LIB ${LIBS}) 
        find_library(${LIB}_LIBPATH ${LIB} PATHS ${LIB_SEARCH_PATH_RELEASE} NO_DEFAULT_PATH)
        list(APPEND DRACO_LIBRARY_RELEASE ${${LIB}_LIBPATH})
        find_library(${LIB}D_LIBPATH ${LIB} PATHS ${LIB_SEARCH_PATH_DEBUG} NO_DEFAULT_PATH)
        list(APPEND DRACO_LIBRARY_DEBUG ${${LIB}D_LIBPATH})
    endforeach()
    select_library_configurations(DRACO)
    target_link_libraries(${TARGET_NAME} ${DRACO_LIBRARY})
endmacro()