macro(TARGET_SPIRV)
    find_package(spirv_cross_core REQUIRED)
    find_package(spirv_cross_reflect REQUIRED)
    find_package(spirv_cross_glsl REQUIRED)
    target_link_libraries(${TARGET_NAME} spirv-cross-core)
    target_link_libraries(${TARGET_NAME} spirv-cross-reflect)
    target_link_libraries(${TARGET_NAME} spirv-cross-glsl)

    find_library(SHADERC_LIBRARY_DEBUG shaderc_combined PATHS ${VCPKG_INSTALL_ROOT}/debug/lib/ NO_DEFAULT_PATH)
    find_library(SHADERC_LIBRARY_RELEASE shaderc_combined PATHS ${VCPKG_INSTALL_ROOT}/lib/ NO_DEFAULT_PATH)
    select_library_configurations(SHADERC)
    target_link_libraries(${TARGET_NAME} ${SHADERC_LIBRARY})
endmacro()
